nombre =input("Ingresar su nombre:")
apellido = input("Ingresar su apellido:")
edad = input("Ingresar su edad:")
CI =input("ingresar su CI:")
print("Su nombre es:", nombre, "Su apeliido es:", apellido, "Su edad es:", edad, "Su CI es:", CI)
